create extension if not exists pgcrypto;

create table if not exists public.threads (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'open' check (status in ('open', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.thread_participants (
  thread_id uuid not null references public.threads(id) on delete cascade,
  participant_id text not null,
  role text not null check (role in ('visitor', 'agent')),
  last_read_at timestamptz,
  primary key (thread_id, participant_id)
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  client_id text not null,
  thread_id uuid not null references public.threads(id) on delete cascade,
  sender_id text not null,
  sender_role text not null check (sender_role in ('visitor', 'agent')),
  body text not null,
  created_at timestamptz not null default now(),
  seq bigint generated by default as identity,
  unique (thread_id, client_id)
);

create index if not exists messages_thread_cursor_idx
  on public.messages (thread_id, created_at desc, seq desc, id desc);

create or replace function public.bump_thread_updated_at()
returns trigger
language plpgsql
as $$
begin
  update public.threads
  set updated_at = now()
  where id = new.thread_id;

  return new;
end;
$$;

drop trigger if exists messages_bump_thread_updated_at on public.messages;
create trigger messages_bump_thread_updated_at
after insert on public.messages
for each row execute function public.bump_thread_updated_at();

alter publication supabase_realtime add table public.messages;
